apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6a8h
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6a8h
    app.kubernetes.io/part-of: ci10t-776-0065-app
  name: devfile-sample-6a8h
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6a8h
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6a8h
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0065-tenant/ci10t-776-0065-app/devfile-sample-6a8h@sha256:59e995dece4a427b4104e290f54b76f17efdc1310c1cd156db8c8a39a1b36e16
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
